all: symptome hygienehinweis hmd hygieneprotokoll checkin checkin_gast checkout

symptome:
	xelatex symptome.tex

hygienehinweis:
	xelatex hygienehinweis.tex

hmd:
	xelatex hmd.tex

hygieneprotokoll:
	xelatex hygieneprotokoll.tex

checkin:
	xelatex checkin.tex

checkin_gast:
	xelatex checkin_gast.tex

checkout:
	xelatex checkout.tex

clean:
	rm *.aux *.log *.out *.pdf
