all: symptome hygienehinweis hmd hygieneprotokoll

symptome:
	xelatex symptome.tex

hygienehinweis:
	xelatex hygienehinweis.tex

hmd:
	xelatex hmd.tex

hygieneprotokoll:
	xelatex hygieneprotokoll.tex

clean:
	rm *.aux *.log *.pdf
