all: symptome hygienehinweis hmd hygieneprotokoll checkin checkout

symptome:
	xelatex symptome.tex

hygienehinweis:
	xelatex hygienehinweis.tex

hmd:
	xelatex hmd.tex

hygieneprotokoll:
	xelatex hygieneprotokoll.tex

checkin:
	xelatex checkin.tex

checkout:
	xelatex checkout.tex

clean:
	rm *.aux *.log *.out *.pdf
